config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :users
    resources :prank_types
    resources :pranks
    resources :type_letters
    resources :letters
    resources :commands
    
    root to: "users#index"

  end

  devise_for :users

  root 'welcome#index'
    
  resources :prank_types
  
  resources :commands do
    collection do
      get 'price'
    end
    resources :charges
  end
  

  
  
  
  
end

app/views/shared/_footer.html.erb
<div id="footer">
  <div class="container">
        <div class="row">
            <div class="col-md-12 col-lg-12">
                <div class="footerContent">
                    <p>&copy;Copyright 2016 - Franck Falcou - Jérémy Petit - All rights reserved.</p><br>
                    <p>3iL Rodez - Promotion 13</p>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/shared/_header.html.erb
<nav class="navbarContainer">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header-personnalized">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to I18n.t('views.application.name', default: 'Le courrier est une farce'), root_path, class: 'headerTitleSite' %>
    </div>
    
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <!-- Login logout link -->
      <div class="login/logout">
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
           <% if user_signed_in? %>
            
            <li>
              <%= link_to('Logout', destroy_user_session_path, :method => :delete, :class => "headerNavElement") %> 
            </li>
            <li>
              <%= link_to('Edit registration', edit_user_registration_path, :class => "headerNavElement") %>
            </li>
            <li>
              <%= link_to('Order', new_command_path, :class => "headerNavElement") %>
            </li>
            <% if current_user.admin %>
              <li>
               <%= link_to('Administration', admin_users_path, :class => "headerNavElement") %>
              </li>
            <% end %>
          <% else %>
            <li>
              <%= link_to('Login', new_user_session_path, :class => "headerNavElement") %>  
            </li>
            <li>
              <%= link_to('Register', new_user_registration_path, :class => "headerNavElement")  %>
            </li>
          <% end %>
          </ul>
        </div>
        <!-- registration link -->
      </div>
    </div>
</nav>