config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :users
    resources :prank_types
    resources :pranks
    resources :type_letters
    resources :letters
    resources :commands
    
    root to: "users#index"

  end

  devise_for :users

  root 'welcome#index'
    
  resources :prank_types
  
  resources :commands do
    collection do
      get 'price'
    end
    resources :charges
  end
  

  
  
  
  
end

app/controllers/admin/prank_types_controller.rb
module Admin
  class PrankTypesController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # simply overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = PrankType.all.paginate(10, params[:page])
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   PrankType.find_by!(slug: param)
    # end

    # See https://administrate-docs.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/prank_types_controller.rb
class PrankTypesController < ApplicationController
  before_action :set_prank_type, only: [:show, :edit, :update, :destroy]

  # GET /prank_types
  # GET /prank_types.json
  def index
    @prank_types = PrankType.all.order(:name)
  end

  # GET /prank_types/1
  # GET /prank_types/1.json
  def show
  end

  # GET /prank_types/new
  def new
    @prank_type = PrankType.new
  end

  # GET /prank_types/1/edit
  def edit
    @prank_type = PrankType.find params[:id]
  end

  # POST /prank_types
  # POST /prank_types.json
  def create
    @prank_type = PrankType.new(prank_type_params)

    respond_to do |format|
      if @prank_type.save
        format.html { redirect_to @prank_type, notice: 'Prank type was successfully created.' }
        format.json { render :show, status: :created, location: @prank_type }
      else
        format.html { render :new }
        format.json { render json: @prank_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /prank_types/1
  # PATCH/PUT /prank_types/1.json
  def update
    respond_to do |format|
      if @prank_type.update(prank_type_params)
        format.html { redirect_to @prank_type, notice: 'Prank type was successfully updated.' }
        format.json { render :show, status: :ok, location: @prank_type }
      else
        format.html { render :edit }
        format.json { render json: @prank_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /prank_types/1
  # DELETE /prank_types/1.json
  def destroy
    @prank_type.destroy
    respond_to do |format|
      format.html { redirect_to prank_types_url, notice: 'Prank type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_prank_type
      @prank_type = PrankType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def prank_type_params
      params.require(:prank_type).permit(:name,:description)
    end
end

app/helpers/prank_types_helper.rb
module PrankTypesHelper
end

app/views/prank_types/_form.html.erb
<%= form_for([@prank_type]) do |f| %>
  <% if @prank_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@prank_type.errors.count, "error") %> prohibited this prank_type from being saved:</h2>

      <ul>
      <% @prank_type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
   <%= f.label :name %> <br>
   <%= f.text_field :name %>
  </div>
  
  <div class="field">
   <%= f.label :description %> <br>
   <%= f.text_field :description %>
  </div>

  <div style="text-align: center; margin:auto">
    <div class="actions">
      <%= f.submit %>
    </div>
  </div>
<% end %>

app/views/prank_types/edit.html.erb
<h1>Editing Prank Type</h1>

<%= render 'form' %>

<%= link_to 'Show', @prank_type %> |
<%= link_to 'Back', prank_types_path %>

app/views/prank_types/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Prank Types</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <table class="table">
     <thead class="thead-default">
          <tr class="active">
           <th>name</th>
           <th>description</th>
           <th>Show</th>
           <th>Edit</th>
           <th>Destroy</th>
         </tr>
     </thead>
     <tbody>
        <% @prank_types.each do |prank_type| %>
         <tr>
          <td><%= prank_type.name %></td>
          <td><%= prank_type.description %></td>
          <td><%= link_to 'Show', prank_type %></td>
          <td><%= link_to 'Edit', edit_prank_type_path(prank_type) %></td>
          <td><%= link_to 'Destroy', prank_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
         </tr>
        <% end %>
     </tbody>
    </table>
  </tbody>
<br>
<div style="text-align: center; margin:auto">
  <button type="button" class="btn btn-primary" style="margin:5%; width= 40%;  padding: 15px 32px;">
    <%= link_to 'New Prank type', new_prank_type_path, {:style=>'color:#FFFFFF; font-size: 250%;', :class => "css_class"} %>
  </button>
</div>

 

app/views/prank_types/new.html.erb
<h1>New Prank Type</h1>

<%= render 'form' %>

<%= link_to 'Back', prank_types_path %>

app/views/prank_types/show.html.erb
<p id="notice"><%= notice %></p>
<h1>View element of "Prank Type"</h1>

<h1 class="display-1">Prank Type</h1><br>

<div class="titleForShow">Name</div>
<p><%= @prank_type.name %></p><br>


<div class="titleForShow">
    Desciption
</div>
<p><%= @prank_type.description %></p>


<%= link_to 'Edit', edit_prank_type_path(@prank_type) %> |
<%= link_to 'Back', prank_types_path %>