config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :users
    resources :prank_types
    resources :pranks
    resources :type_letters
    resources :letters
    resources :commands
    
    root to: "users#index"

  end

  devise_for :users

  root 'welcome#index'
    
  resources :prank_types
  
  resources :commands do
    collection do
      get 'price'
    end
    resources :charges
  end
  

  
  
  
  
end

app/models/command.rb
class Command < ActiveRecord::Base
    belongs_to :prank_type
    belongs_to :prank
    belongs_to :letter
    belongs_to :type_letter
    
    #attr_accessible :prank_type_id, :prank_id, :type_letter_id, :letter_id, :message, :totalPrice
end

app/controllers/admin/commands_controller.rb
module Admin
  class CommandsController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # simply overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Command.all.paginate(10, params[:page])
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Command.find_by!(slug: param)
    # end

    # See https://administrate-docs.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/commands_controller.rb
class CommandsController < ApplicationController
  before_action :set_command, only: [:show, :edit, :update, :destroy]
  
  def price
    @prank = Prank.find(params[:prank_id])
    @letter = Letter.find(params[:letter_id])
    @price = (@prank.price*@letter.weight/100)+@letter.price
  end

  # GET /commands
  # GET /commands.json
  def index
    @commands = Command.all
    @command = Command.new
  end

  # GET /commands/1
  # GET /commands/1.json
  def show
  end

  # GET /commands/new
  def new
    @command = Command.new
    @command.prank_type = @prank_type
    @command.prank = @prank
    @command.letter = @letter
    @command.type_letter = @type_letter
    
  end

  # GET /commands/1/edit
  def edit
  end

  # POST /commands
  # POST /commands.json
  def create
    @command = Command.new(command_params)
    # @command = Command.new(params[:command])

    respond_to do |format|
      format.js
      if @command.save
        format.html { redirect_to new_command_charge_path(@command), notice: 'Command was successfully created.' }
        format.json { render :show, status: :created, location: @command }
      else
        format.html { render :new }
        format.json { render json: @command.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /commands/1
  # PATCH/PUT /commands/1.json
  def update
    respond_to do |format|
      if @command.update(command_params)
        format.html { redirect_to @command, notice: 'Command was successfully updated.' }
        format.json { render :show, status: :ok, location: @command }
      else
        format.html { render :edit }
        format.json { render json: @command.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /commands/1
  # DELETE /commands/1.json
  def destroy
    @command.destroy
    respond_to do |format|
      format.html { redirect_to commands_url, notice: 'Command was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_command
      @command = Command.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def command_params
      params.require(:command).permit(:prank_type_id, :prank_id, :type_letter_id, :letter_id, :message, :totalPrice, :Address)
    end
end

app/helpers/commands_helper.rb
module CommandsHelper
end

app/views/commands/_form.html.erb
<%= form_for(@command) do |f| %>
  <div class=formOrder>
    <div class="field">
      <%= f.label :prank_type, :class => "labelOrder"%> <br />
      <%= f.collection_select :prank_type_id, PrankType.order(:name), :id, :name, include_blank: true, :class => 'collectionOrder' %><br />
    </div>
    <div class="field">
      <%= f.label :prank, :class => "labelOrder" %> <br />
      <%= f.grouped_collection_select :prank_id, PrankType.order(:name), :pranks, :name, :id, :name, include_blank: true, :class => "collectionOrder" %>
    </div>
    <br>
    <br>
    <div class="field">
      <%= f.label :type_letter, :class => "labelOrder" %> <br />
      <%= f.collection_select :type_letter_id, TypeLetter.order(:name), :id, :name, include_blank: true %><br />
    </div>
    <div class="field">
      <%= f.label :letter, :class => "labelOrder" %> <br />
      <%= f.grouped_collection_select :letter_id, TypeLetter.order(:name), :letters, :name, :id, :name, include_blank: true %>
    </div>
    
     <div class="field">
      <%= link_to 'Calculer le prix de votre commande', '#', class: 'btn btn-success btnOrderCalc', id: 'calc_price' %>
    </div>
    
    <div class="containerTextfieldForm">
      <%= f.label :message, :class => "labelOrder" %> <br />
      <%= f.text_field :message, autocomplete: "off",  class: 'textfieldForForm' %><br>
      
      <%= f.label :totalPrice, :class => "labelOrder" %> <br /> 
      <%= f.text_field :totalPrice, autocomplete: "off", :readonly => true,  class: 'textfieldForForm' %>
    </div>
    <div class="containerTextfieldForm">
      <%= f.label :Address, :class => "labelOrder" %> <br />
      <%= f.text_field :Address, :id => "user_input_autocomplete_address", autocomplete: "off", class: 'textfieldForForm' %><br>
      <div class="field">
        <input id="street_number" name="street_number" class="textfieldForForm" disabled>
        <input id="route" name="route" class="textfieldForForm" disabled>
        <input id="locality" name="locality" class="textfieldForForm" disabled>
        <input id="country" name="country" class="textfieldForForm" disabled>
      </div>
    </div>
   
    <div class="containerTextfieldForm">
      <div class="actions">
        <%= f.submit "Commander", class: 'buttonForm' %>   
      </div>
    </div>
  </div>
<% end %>

<!-- Custom JS code to bind to Autocomplete API -->
<!-- find it here: https://github.com/lewagon/google-place-autocomplete/blob/gh-pages/autocomplete.js -->
<!-- We'll detail this file in the article -->
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?libraries=places&key=AIzaSyDGYsbdMyZtVathV3VFLRTCH1OGD5PSygc">
</script>
<script>
  function initializeAutocomplete(id) {
    var element = document.getElementById(id);
    if (element) {
      var autocomplete = new google.maps.places.Autocomplete(element, { types: ['geocode'] });
      google.maps.event.addListener(autocomplete, 'place_changed', onPlaceChanged);
    }
  }

  function onPlaceChanged() {
    var place = this.getPlace();
    // console.log(place);  // Uncomment this line to view the full object returned by Google API.
  
    for (var i in place.address_components) {
      var component = place.address_components[i];
      for (var j in component.types) {  // Some types are ["country", "political"]
        var type_element = document.getElementById(component.types[j]);
        if (type_element) {
          type_element.value = component.long_name;
        }
      }
    }
  }
  google.maps.event.addDomListener(window, 'load', function() {
    initializeAutocomplete('user_input_autocomplete_address');
  }); 
</script> 


<script>
  jQuery(function() {
    var states;
    $('#command_letter_id').parent().hide();
    states = $('#command_letter_id').html();
    console.log(states);
    $('#command_type_letter_id').change(function() {
      var country, escaped_country, options;
      country = $('#command_type_letter_id :selected').text();
      escaped_country = country.replace(/([ #;&,.+*~\':"!^$[\]()=>|\/@])/g, '\\$1');
      options = $(states).filter("optgroup[label=" + escaped_country + "]").html();
      console.log(options);
      if (options) {
        $('#command_letter_id').html(options);
        $('#command_letter_id').parent().show();
      } else {
        $('#command_letter_id').empty();
        $('#command_letter_id').parent().hide();
      }
    });

    var states2;
    $('#command_prank_id').parent().hide();
    states2 = $('#command_prank_id').html();
    console.log(states2);
    $('#command_prank_type_id').change(function() {
      var country2, escaped_country2, options2;
      country2 = $('#command_prank_type_id :selected').text();
      escaped_country2 = country2.replace(/([ #;&,.+*~\':"!^$[\]()=>|\/@])/g, '\\$1');
      options2 = $(states2).filter("optgroup[label=" + escaped_country2 + "]").html();
      console.log(options2);
      if (options2) {
        $('#command_prank_id').html(options2);
        $('#command_prank_id').parent().show();
      } else {
        $('#command_prank_id').empty();
        $('#command_prank_id').parent().hide();
      }
    });
    
    $('#calc_price').on('click', function() {
      prank_id = $('#command_prank_id :selected').val();
      letter_id = $('#command_letter_id :selected').val();
      
      $.ajax({
        url: "/commands/price?prank_id=" + prank_id + "&letter_id=" + letter_id
      }).done(function(html) {
        $("#command_totalPrice").val(html);
      });
    });
  });
  
  

</script>

app/views/commands/edit.html.erb
<h1>Editing Command</h1>

<%= render 'form' %>

<%= link_to 'Show', @command %> |
<%= link_to 'Back', commands_path %>

app/views/commands/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Commands</h1>

<table>
  <thead>
    <tr>
      <th colspan="3">
        <%= form_for @command do |f| %>
        
          <%= f.label :prank_type %> <br />
          <%= f.collection_select :prank_type_id, PrankType.all.order(:name), :name, :name, include_blank: true %><br />
          
          <%= f.label :prank %> <br />
          <%= f.grouped_collection_select :prank_id, PrankType.order(:name), :pranks, :name, :id, :name, include_blank: true %>
          
          <br>
          <br>
          <div class="actions">
            <%= f.submit %>   
          </div>
        <% end %>
        
      </th>
    </tr>
  </thead>

  <tbody>
    <% @commands.each do |command| %>
      <tr>
        <td><%= link_to 'Show', command %></td>
        <td><%= link_to 'Edit', edit_command_path(command) %></td>
        <td><%= link_to 'Destroy', command, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Command', new_command_path %>

app/views/commands/new.html.erb
<h1 class="titleOrder">New Order</h1>

<%= render 'form' %>
<div class="containerTextfieldForm">
<%= link_to 'Back', commands_path %>
</div>

app/views/commands/price.json.erb
<%= @price %>

app/views/commands/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_command_path(@command) %> |
<%= link_to 'Back', commands_path %>